/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mumu
 * 
 */
import java.awt.Toolkit;
public class Account_Info extends javax.swing.JFrame {

    /**
     * Creates new form Account_Info
     */

    public Account_Info() {
        initComponents();
        setTitle("Home");
        PhoneLabel.setText("0"+Variables.PhoneNo);
        NameLable.setText(Variables.Name);
        CurrentBlance.setText(Float.toString(Variables.Blance));
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x=800;
        int y=600;
        this.setSize(x,y);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SendMoney = new javax.swing.JButton();
        CashOut = new javax.swing.JButton();
        History = new javax.swing.JButton();
        UdateInfo = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        Payment = new javax.swing.JButton();
        MobileRecharge = new javax.swing.JButton();
        PhoneLabel = new javax.swing.JLabel();
        NameLable = new javax.swing.JLabel();
        CurrentBlance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        getContentPane().setLayout(null);

        SendMoney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SendMoney.setText("SEND MONEY");
        SendMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMoneyActionPerformed(evt);
            }
        });
        getContentPane().add(SendMoney);
        SendMoney.setBounds(220, 100, 360, 40);

        CashOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CashOut.setText("CASH OUT");
        CashOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashOutActionPerformed(evt);
            }
        });
        getContentPane().add(CashOut);
        CashOut.setBounds(220, 160, 360, 37);

        History.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        History.setText("HISTORY");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });
        getContentPane().add(History);
        History.setBounds(220, 310, 360, 35);

        UdateInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UdateInfo.setText("UPDATE INFORMATION");
        UdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdateInfoActionPerformed(evt);
            }
        });
        getContentPane().add(UdateInfo);
        UdateInfo.setBounds(220, 360, 360, 40);

        Return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Return.setText("Back");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return);
        Return.setBounds(640, 490, 100, 37);

        Payment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Payment.setText("PAYMENT");
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });
        getContentPane().add(Payment);
        Payment.setBounds(220, 210, 360, 36);

        MobileRecharge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MobileRecharge.setText("MOBILE RECHARGE");
        MobileRecharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileRechargeActionPerformed(evt);
            }
        });
        getContentPane().add(MobileRecharge);
        MobileRecharge.setBounds(220, 260, 360, 40);

        PhoneLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        getContentPane().add(PhoneLabel);
        PhoneLabel.setBounds(40, 18, 250, 30);

        NameLable.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(NameLable);
        NameLable.setBounds(40, 70, 230, 30);

        CurrentBlance.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(CurrentBlance);
        CurrentBlance.setBounds(570, 30, 140, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CURRENT BALANCE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 200, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user info bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMoneyActionPerformed
        // TODO add your handling code here:
        Send_Money one = new Send_Money();
        one.setVisible(true);
        dispose();
    }//GEN-LAST:event_SendMoneyActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        // TODO add your handling code here:
        Payment two = new Payment();
        two.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_PaymentActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        // TODO add your handling code here:
        History three= new History();
        three.setVisible(true);
        dispose();
    }//GEN-LAST:event_HistoryActionPerformed

    private void CashOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashOutActionPerformed
        // TODO add your handling code here:
        Cash_Out four = new Cash_Out();
        four.setVisible(true);
        dispose();
    }//GEN-LAST:event_CashOutActionPerformed

    private void MobileRechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileRechargeActionPerformed
        // TODO add your handling code here:
        Mobile_Recharge five = new Mobile_Recharge();
        five.setVisible(true);
        dispose();
    }//GEN-LAST:event_MobileRechargeActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        Login_Signup six = new Login_Signup();
        six.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnActionPerformed

    private void UdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdateInfoActionPerformed
        // TODO add your handling code here:
     Update seven = new Update();
     seven.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_UdateInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CashOut;
    private javax.swing.JLabel CurrentBlance;
    private javax.swing.JButton History;
    private javax.swing.JButton MobileRecharge;
    private javax.swing.JLabel NameLable;
    private javax.swing.JButton Payment;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JButton Return;
    private javax.swing.JButton SendMoney;
    private javax.swing.JButton UdateInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
