
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mumu
 */
public class Cash_Out extends javax.swing.JFrame {

    /**
     * Creates new form Mobile_Recharge
     */
    public Cash_Out() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x=800;
        int y=600;
        this.setSize(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Number = new javax.swing.JTextField();
        Ammount = new javax.swing.JTextField();
        cash_out = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Number.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberActionPerformed(evt);
            }
        });
        getContentPane().add(Number);
        Number.setBounds(190, 170, 460, 40);

        Ammount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(Ammount);
        Ammount.setBounds(190, 300, 460, 40);

        cash_out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cash_out.setText("CASH OUT");
        cash_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_outActionPerformed(evt);
            }
        });
        getContentPane().add(cash_out);
        cash_out.setBounds(350, 390, 170, 50);

        Return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Return.setText("BACK");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return);
        Return.setBounds(630, 500, 110, 38);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ENTER NUMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 110, 246, 52);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ENTER AMOUNT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 250, 265, 42);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cash out.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 810, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        Account_Info one = new Account_Info();
        one.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnActionPerformed

    private void cash_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_outActionPerformed
        // TODO add your handling code here:
         Connection connection;
        PreparedStatement pst;
        ResultSet result = null, stockResult;
        int uname = Integer.parseInt(Number.getText());
        String RNumber = Integer.toString(uname);
        int flag=0;
        try {
            connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BankingService", "sa", "123456");
            pst = connection.prepareStatement("SELECT * FROM UserInfo where PhoneNo = " + RNumber);
            result = pst.executeQuery();
            int money = Integer.parseInt(Ammount.getText());
            if (Variables.Blance>money) {
               while (result.next()) {
                if (result.getString("PhoneNo").equals(RNumber) && !(Variables.PhoneNo).equals(RNumber)) {
                    pst = connection.prepareStatement("insert into TransTable values(?,?,?,?,?,?)");
                    pst.setInt(1, Variables.UserId);
                    pst.setString(2, Variables.PhoneNo);
                    pst.setString(3, RNumber);
                    pst.setString(4, "Cash Out");
                    pst.setString(5, Ammount.getText());
                    int reciverID= result.getInt("UserId");

                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                    Date date = new Date();
                    //System.out.println(date.toString()); //2016/11/16 12:08:43
                    pst.setString(6, dateFormat.format(date));

                    pst.executeUpdate();
                    float percent = money/20;
                    Variables.Blance=Variables.Blance-money-percent;
                    pst=connection.prepareStatement("UPDATE BlanceTable SET CurrentBlance = ?  where UserId ="+Variables.UserId);
                    pst.setFloat(1, Variables.Blance );
                     pst.executeUpdate();
                     
                     pst = connection.prepareStatement("SELECT * FROM BlanceTable where UserId = " +reciverID);
                     result = pst.executeQuery();
                     while (result.next()) { 
                         int reciverBalnce= result.getInt("CurrentBlance");
                         reciverBalnce=reciverBalnce+money;
                         pst=connection.prepareStatement("UPDATE BlanceTable SET CurrentBlance = ?  where UserId ="+reciverID);
                         pst.setInt(1, reciverBalnce );
                         pst.executeUpdate();
                         
                        
                    }
                     
                    JOptionPane.showMessageDialog(null, "Cash out "+money+" Successful Charge "+percent+" ");
                    Number.setText(" ");
                    Ammount.setText(" ");
                     pst = connection.prepareStatement("insert into ProfitTable values(?,?,?,?,?)");
                    pst.setInt(1, Variables.UserId);
                    pst.setString(2, Variables.PhoneNo);
                    pst.setString(3, "Cash Out");
                    pst.setFloat(4, percent);
                    

                    
                    
                    //System.out.println(date.toString()); //2016/11/16 12:08:43
                    pst.setString(5, dateFormat.format(date));

                    pst.executeUpdate();

                } else {
                    flag=1;
                    JOptionPane.showMessageDialog(null, "You Can't Send Yourself Money");
                }
            }
                if (!result.next() && flag!=0) {
                    JOptionPane.showMessageDialog(null, "User Not Found");
                }
            }
            else{
                 JOptionPane.showMessageDialog(null, "You DO Not Have Sufficient Money");
            }
          

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cash_outActionPerformed

    private void NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mobile_Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mobile_Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mobile_Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mobile_Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cash_Out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ammount;
    private javax.swing.JTextField Number;
    private javax.swing.JButton Return;
    private javax.swing.JButton cash_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
