
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mumu
 */
public class Login_Signup extends javax.swing.JFrame {

    /**
     * Creates new form Login_Signup
     */
    public Login_Signup() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x=800;
        int y=600;
        this.setSize(x,y);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign_UP = new javax.swing.JButton();
        UserNameInput = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Sign_UP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sign_UP.setText("SIGN UP");
        Sign_UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_UPActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_UP);
        Sign_UP.setBounds(290, 470, 170, 40);

        UserNameInput.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        UserNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameInputActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameInput);
        UserNameInput.setBounds(150, 150, 490, 50);

        Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Login.setText("SIGN IN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(290, 400, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ENTER USER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 80, 360, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ENTER PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 230, 220, 40);

        PasswordInput.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        getContentPane().add(PasswordInput);
        PasswordInput.setBounds(150, 300, 490, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log in bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_UPActionPerformed
        // TODO add your handling code here:
       UserInfo userinfo = new UserInfo();
       userinfo.setVisible(true);
        dispose();

    }//GEN-LAST:event_Sign_UPActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        Connection connection;
        PreparedStatement pst;
        ResultSet result = null, stockResult;
        int uname = Integer.parseInt(UserNameInput.getText());
        String username = Integer.toString(uname);
        //System.out.println(username);
        char[] pwd = PasswordInput.getPassword();
        String password = new String(pwd);
        try {
            connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BankingService", "sa", "123456");
            pst = connection.prepareStatement("SELECT * FROM UserInfo where PhoneNo = " +username);
            result = pst.executeQuery();
            while(result.next()){
            if (result.getString("PhoneNo").equals(username) && result.getString("PasswordNo").equals(password) && result.getString("AccountType").equals("1") ) {
                UserNameInput.setText(" ");
                PasswordInput.setText(" ");
                Variables.PhoneNo=username;
                Variables.UserId=result.getInt("UserId");
                //System.out.println(Variables.UserId);
                Variables.Name=result.getString("FirstName");
                pst = connection.prepareStatement("SELECT * FROM BlanceTable where UserId = " +Variables.UserId);
                result = pst.executeQuery();
                while (result.next()) {                    
                    Variables.Blance=result.getInt("CurrentBlance");
                }
                
                Account_Info Frist = new Account_Info();
                Frist.setVisible(true);
                dispose();
            }
            else if(result.getString("PhoneNo").equals(username) && result.getString("PasswordNo").equals(password) && result.getString("AccountType").equals("2")){
               UserNameInput.setText(" ");
                PasswordInput.setText(" ");
                Variables.PhoneNo=username;
                Variables.UserId=result.getInt("UserId");
                System.out.println(Variables.UserId);
                Variables.Name=result.getString("FirstName");
                pst = connection.prepareStatement("SELECT * FROM BlanceTable where UserId = " +Variables.UserId);
                result = pst.executeQuery();
                while (result.next()) {                    
                    Variables.Blance=result.getInt("CurrentBlance");
                }
                
                Account_Info_Agent Frist = new Account_Info_Agent();
                Frist.setVisible(true);
                dispose();
            }
             else if(result.getString("PhoneNo").equals(username) && result.getString("PasswordNo").equals(password) && result.getString("AccountType").equals("3")){
                UserNameInput.setText(" ");
                PasswordInput.setText(" ");
                Variables.PhoneNo=username;
                Variables.UserId=result.getInt("UserId");
                Variables.Name=result.getString("FirstName");
                Account_Info_admin Second = new Account_Info_admin();
                Second.setVisible(true);
                dispose();
            }
            else
            {
               JOptionPane.showMessageDialog(null, "Login Failed"); 
            }
            }
            
           
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_LoginActionPerformed

    private void UserNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Signup().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton Sign_UP;
    private javax.swing.JTextField UserNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
