
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mumu
 */
public class Update extends javax.swing.JFrame {

   
  
    /**
     * Creates new form UserInfo
     */
    int flag=0;
    public Update() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        NationalId = new javax.swing.JTextField();
        BirthCertificateNo = new javax.swing.JTextField();
        PresentAddress = new javax.swing.JTextField();
        PermanentAddress = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        ReferanceId = new javax.swing.JTextField();
        SignUp = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        AccoutType = new javax.swing.JComboBox<>();
        GetInfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PHONE NO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 227, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FIRST NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 55, 227, 33);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("LAST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 137, 212, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("MIDDLE NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 94, 212, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DATE OF BIRTH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 223, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("NATIONAL ID NO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 225, 227, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("BIRTH CERTIFICATE NO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 271, 223, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("PRESENT ADDRESS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 312, 227, 31);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("PERMANENT ADDRESS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 357, 227, 36);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 405, 227, 31);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("REFERANCE ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 450, 227, 30);

        PhoneNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PhoneNo);
        PhoneNo.setBounds(251, 11, 472, 33);

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(FirstName);
        FirstName.setBounds(251, 55, 472, 33);

        LastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(LastName);
        LastName.setBounds(255, 137, 468, 37);

        MiddleName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameActionPerformed(evt);
            }
        });
        getContentPane().add(MiddleName);
        MiddleName.setBounds(251, 94, 472, 32);

        DOB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(DOB);
        DOB.setBounds(251, 183, 472, 31);

        NationalId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(NationalId);
        NationalId.setBounds(255, 228, 472, 32);

        BirthCertificateNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(BirthCertificateNo);
        BirthCertificateNo.setBounds(255, 275, 472, 31);

        PresentAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PresentAddress);
        PresentAddress.setBounds(255, 315, 472, 31);

        PermanentAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PermanentAddress);
        PermanentAddress.setBounds(255, 362, 472, 32);

        Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(255, 408, 472, 31);

        ReferanceId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(ReferanceId);
        ReferanceId.setBounds(255, 450, 472, 30);

        SignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SignUp.setText("UPDATE");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp);
        SignUp.setBounds(440, 530, 127, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("ACCOUNT TYPE");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 491, 227, 35);

        AccoutType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AccoutType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER", "AGENT" }));
        AccoutType.setToolTipText("");
        getContentPane().add(AccoutType);
        AccoutType.setBounds(255, 491, 472, 35);

        GetInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GetInfo.setText("GET INFO");
        GetInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetInfoActionPerformed(evt);
            }
        });
        getContentPane().add(GetInfo);
        GetInfo.setBounds(10, 530, 125, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 530, 81, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update usr.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel12.setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -100, 840, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
    
    Connection connection;
    PreparedStatement pst;
    ResultSet result = null, stockResult;
    if(flag==1){
  try {
   
   //connection Establishment
   String username = PhoneNo.getText(); 
   connection=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BankingService","sa","123456");
   pst=connection.prepareStatement("UPDATE UserInfo SET FirstName = ? , LastName = ?, MiddleName = ? ,DateOfBirth = ? ,NationalId = ? ,BirthCertificate = ? , PresentAddress= ? ,PremanentAddress = ? ,PasswordNo = ? ,ReferenceId = ? where PhoneNo ="+username);
  
   
   pst.setString(1, FirstName.getText());
   pst.setString(2, LastName.getText());
   pst.setString(3, MiddleName.getText());
   pst.setString(4, DOB.getText());
   pst.setString(5, NationalId.getText());
   pst.setString(6, BirthCertificateNo.getText());
   pst.setString(7, PresentAddress.getText());
   pst.setString(8, PermanentAddress.getText());
   pst.setString(9, Password.getText());
   pst.setString(10, ReferanceId.getText());
  
  
  
   pst.executeUpdate();
   JOptionPane.showMessageDialog(null, "Update successful");
   PhoneNo.setText(" ");
   FirstName.setText(" ");
   FirstName.setText(" ");
   LastName.setText(" ");
   MiddleName.setText(" ");
   DOB.setText(" ");
   NationalId.setText(" ");
   BirthCertificateNo.setText(" ");
   PresentAddress.setText(" ");
   PermanentAddress.setText(" ");
   Password.setText(" ");
   ReferanceId.setText(" ");
;
  }catch(SQLException e) {
      e.printStackTrace();
   JOptionPane.showMessageDialog(null, "Update not successful");
  }
    }
    else{
        JOptionPane.showMessageDialog(null, "Please press get info");
    }
        
    }//GEN-LAST:event_SignUpActionPerformed

    private void GetInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetInfoActionPerformed
        // TODO add your handling code here:
    Connection connection;
        PreparedStatement pst;
        ResultSet result = null, stockResult;
        String username = PhoneNo.getText();
        System.out.println(username);
        
        try {
            connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BankingService", "sa", "123456");
            pst = connection.prepareStatement("SELECT * FROM UserInfo where PhoneNo = " +Variables.PhoneNo);
            result = pst.executeQuery();
            while(result.next()){
               FirstName.setText(result.getString("FirstName"));
               LastName.setText(result.getString("LastName"));
               MiddleName.setText(result.getString("MiddleName"));
               DOB.setText(result.getString("DateOfBirth"));
               NationalId.setText(result.getString("NationalId"));
               BirthCertificateNo.setText(result.getString("BirthCertificate"));
               PresentAddress.setText(result.getString("PresentAddress"));
               PermanentAddress.setText(result.getString("PremanentAddress"));
               Password.setText(result.getString("PasswordNo"));
               ReferanceId.setText(result.getString("ReferenceId"));
               flag=1;
            }
            
           
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_GetInfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Account_Info one = new Account_Info();
        one.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddleNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccoutType;
    private javax.swing.JTextField BirthCertificateNo;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField FirstName;
    private javax.swing.JButton GetInfo;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JTextField NationalId;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField PermanentAddress;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField PresentAddress;
    private javax.swing.JTextField ReferanceId;
    private javax.swing.JButton SignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
